#!/bin/bash

usage() {
    echo "Usage:"
    echo "  ./reduce_phoronix --sub_test <test_running> --tmp_name <output_temp_file>"
    echo "Options:"
    echo "  -h          Show help"
    echo "  --sub_test  Specify the test to run"
    echo "  --tmp_file  Specify output temp file"
    exit 1
}

# Check if an argument is passed
if [ $# -eq 0 ]; then
    usage
fi

# Initialize variables
test_running="none"
tmp_file="none"
# Process command line arguments
while [ $# -gt 0 ]; do
    case $1 in
        -h)
            usage
            ;;
        --sub_test)
            test_running=$2
            shift 2
            ;;
        --tmp_file)
            tmp_file=$2
            shift 2
            ;;
        *)
            usage
            ;;
    esac
done

# Check if a test to run is designated
if [ "$test_running" == "none" ]; then
    echo "You need to designate a test to run."
    usage
fi
if [ "$tmp_file" == "none" ]; then
    echo "You need a file to output to"
    usage
fi

if [[ "$test_running" == "cockroach" ]]; then
    echo "Workload:Concurrency:Average:Deviation" > "$tmp_file"
    # Read and process the results file
    while IFS= read -r line; do
        # Check for lines containing workload and concurrency
        if [[ $line == *Workload* ]]; then
            # Extract Workload and Concurrency
            workload=$(echo "$line" | awk -F ': ' '{print $2}' | awk -F ' - ' '{print $1}')
            concurrency=$(echo "$line" | awk -F ': ' '{print $3}' | tr -d ':')
        fi
        if [[ $line == *Average* ]]; then
            # Extract Average
            average=$(echo "$line" | awk -F ': ' '{print $2}' | awk '{print $1}')
        fi
        if [[ $line == *Deviation* ]]; then
            # Extract Deviation
            deviation=$(echo "$line" | awk -F ': ' '{print $2}' | tr -d '%')
            # Append the extracted information to the output file
            echo "$workload:$concurrency:$average:$deviation" >> "$tmp_file"
        fi
        rm "$tmp_file"
    done < /tmp/results_phoronix_"$test_running"_tuned_*.out
elif [[ "$test_running" == "redis" ]]; then
    echo "Test:ParallelConnections:Average:Deviation" > "$tmp_file"
    # Read and process the results file
    while IFS= read -r line; do
        # Check for lines containing Test and Parallel Connections
        if [[ $line == *"Test:"* && $line == *"Parallel Connections:"* ]]; then
            # Extract Test and Parallel Connections
            test=$(echo "$line" | awk -F 'Test: ' '{print $2}' | awk -F ' - ' '{print $1}')
            parallel_connections=$(echo "$line" | awk -F ': ' '{print $3}' | tr -d ':')
        fi
        if [[ $line == *"Average:"* ]]; then
            # Extract Average
            average=$(echo "$line" | awk -F ': ' '{print $2}' | awk '{print $1}')
        fi
        if [[ $line == *"Deviation:"* ]]; then
            # Extract Deviation
            deviation=$(echo "$line" | awk -F ': ' '{print $2}' | tr -d '%')
            # Append the extracted information to the output file
            echo "$test:$parallel_connections:$average:$deviation" >> "$tmp_file"
        fi
        rm "$tmp_file"
    done < /tmp/results_phoronix_"$test_running"_tuned_*.out
else
    echo "Unsupported test: $test_running"
    exit 1
fi